#pragma once
namespace thebanana {
#ifdef BANANA_WINDOWS
	enum key {
		key_esc = DIK_ESCAPE,
		key_f1 = DIK_F1,
		key_f2 = DIK_F2,
		key_f3 = DIK_F3,
		key_f4 = DIK_F4,
		key_f5 = DIK_F5,
		key_f6 = DIK_F6,
		key_f7 = DIK_F7,
		key_f8 = DIK_F8,
		key_f9 = DIK_F9,
		key_f10 = DIK_F10,
		key_f11 = DIK_F11,
		key_f12 = DIK_F12,
		key_0 = DIK_0,
		key_1 = DIK_1,
		key_2 = DIK_2,
		key_3 = DIK_3,
		key_4 = DIK_4,
		key_5 = DIK_5,
		key_6 = DIK_6,
		key_7 = DIK_7,
		key_8 = DIK_8,
		key_9 = DIK_9,
		key_q = DIK_Q,
		key_w = DIK_W,
		key_e = DIK_E,
		key_r = DIK_R,
		key_t = DIK_T,
		key_y = DIK_Y,
		key_u = DIK_U,
		key_i = DIK_I,
		key_o = DIK_O,
		key_p = DIK_P,
		key_a = DIK_A,
		key_s = DIK_S,
		key_d = DIK_D,
		key_f = DIK_F,
		key_g = DIK_G,
		key_h = DIK_H,
		key_j = DIK_J,
		key_k = DIK_K,
		key_l = DIK_L,
		key_z = DIK_Z,
		key_x = DIK_X,
		key_c = DIK_C,
		key_v = DIK_V,
		key_b = DIK_B,
		key_n = DIK_N,
		key_m = DIK_M,
		key_ctrl = DIK_LCONTROL,
		key_shift = DIK_LSHIFT,
		key_space = DIK_SPACE,
		key_enter = DIK_RETURN,
		key_tab = DIK_TAB,
		key_alt = DIK_LALT,
	};
#else
	enum key {
		key_ctrl,
		key_shift,
		key_alt,
		key_n,
		key_o,
		key_s,
		key_w,
		key_e,
		key_r,
		key_t,
	};
#endif
	enum mouse_button {
		left_click = 0,
		right_click = 1,
		mouse_wheel_click = 2,
		back = 3,
	};
}